---
version: '3.9'
services:
  db:
    image: postgres
    volumes: [data:/var/lib/postgresql/data]
    command: -p $DATABASE_PORT
    environment:
      POSTGRES_USER: $DATABASE_USER
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
      POSTGRES_DB: $DATABASE_NAME
    ports: [$DATABASE_PORT:$DATABASE_PORT]
  db_test:
    image: postgres
    volumes: [data_test:/var/lib/postgresql/data]
    command: -p $DATABASE_TEST_PORT
    environment:
      POSTGRES_USER: $DATABASE_USER
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
      POSTGRES_DB: $DATABASE_NAME
    ports: [$DATABASE_TEST_PORT:$DATABASE_TEST_PORT]
volumes:
  data:
  data_test:
